// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcnKV39DM5B1hqPX3m0PkmJSOqxiDi0Qk',
    appId: '1:288993934101:web:08b13152735b42dfc2071c',
    messagingSenderId: '288993934101',
    projectId: 'sportify-b1705',
    authDomain: 'sportify-b1705.firebaseapp.com',
    storageBucket: 'sportify-b1705.firebasestorage.app',
    measurementId: 'G-W0ZPGV6470',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrAHYLQIvTbimzBboEGJ4jFXaVWiuCPY4',
    appId: '1:288993934101:android:89ef224cac4a4e21c2071c',
    messagingSenderId: '288993934101',
    projectId: 'sportify-b1705',
    storageBucket: 'sportify-b1705.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfHgOnMuK_DhRUf0NkD5LVe0It3m79o2U',
    appId: '1:288993934101:ios:1ca563b1703c6ca5c2071c',
    messagingSenderId: '288993934101',
    projectId: 'sportify-b1705',
    storageBucket: 'sportify-b1705.firebasestorage.app',
    iosBundleId: 'com.sportify.sportify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfHgOnMuK_DhRUf0NkD5LVe0It3m79o2U',
    appId: '1:288993934101:ios:1ca563b1703c6ca5c2071c',
    messagingSenderId: '288993934101',
    projectId: 'sportify-b1705',
    storageBucket: 'sportify-b1705.firebasestorage.app',
    iosBundleId: 'com.sportify.sportify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcnKV39DM5B1hqPX3m0PkmJSOqxiDi0Qk',
    appId: '1:288993934101:web:411e601986d03358c2071c',
    messagingSenderId: '288993934101',
    projectId: 'sportify-b1705',
    authDomain: 'sportify-b1705.firebaseapp.com',
    storageBucket: 'sportify-b1705.firebasestorage.app',
    measurementId: 'G-0T713Y9KBN',
  );
}
